In [2]:
from xgboost import XGBClassifier
import pandas as pd 
from paths import DATA_PATH, MODEL_PATH

In [3]:
df = pd.read_parquet(DATA_PATH / 'grouped_data_with_name.parquet')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 21 columns):
 #   Column                   Dtype
---  ------                   -----
 0   amount                   float64
 1   type_CASH_IN             int64
 2   type_CASH_OUT            int64
 3   type_DEBIT               int64
 4   type_PAYMENT             int64
 5   type_TRANSFER            int64
 6   orig_tx_count_same_step  int64
 7   orig_tx_cumcount         int64
 8   orig_prev_amount         float64
 9   orig_amount_ratio        float64
 10  steps_since_last_tx      float64
 11  dest_tx_cumcount         int64
 12  dest_prev_amount         float64
 13  dest_amount_ratio        float64
 14  dest_steps_since_last    float64
 15  pair_tx_cumcount         int64
 16  is_new_dest              int64
 17  pair_total_amount        float64
 18  hour_of_day              int64
 19  day                      int64
 20  is_night                 int64
dtypes: float64(8), int64(13)
memory usage: 1019.4 MB

In [5]:
df[(df['isFraud'] == 1) & (df['type_CASH_IN'] == 1)].head()

Empty DataFrame
Columns: [amount, isFraud, type_CASH_IN, type_CASH_OUT, type_DEBIT, type_PAYMENT, type_TRANSFER, orig_tx_count_same_step, orig_tx_cumcount, orig_prev_amount, orig_amount_ratio, steps_since_last_tx, dest_tx_cumcount, dest_prev_amount, dest_amount_ratio, dest_steps_since_last, pair_tx_cumcount, is_new_dest, pair_total_amount, hour_of_day, day, is_night]
Index: []

[0 rows x 22 columns]

In [ ]:
df.drop(columns=['isFraud'], inplace=True)

In [33]:
transaction = df.tail(3)
transaction

,amount,type_CASH_IN,type_CASH_OUT,type_DEBIT,type_PAYMENT,type_TRANSFER,orig_tx_count_same_step,orig_tx_cumcount,orig_prev_amount,orig_amount_ratio,...,dest_tx_cumcount,dest_prev_amount,dest_amount_ratio,dest_steps_since_last,pair_tx_cumcount,is_new_dest,pair_total_amount,hour_of_day,day,is_night
6362617,6311409.28,0,0,0,0,1,1,1,0.0,0.0,...,1,0.0,0.0,-1.0,0,1,6311409.28,23,30,1
6362618,850002.52,0,0,0,0,1,1,1,0.0,0.0,...,1,0.0,0.0,-1.0,0,1,850002.52,23,30,1
6362619,339682.13,0,0,0,0,1,1,1,0.0,0.0,...,1,0.0,0.0,-1.0,0,1,339682.13,23,30,1

In [27]:
model = XGBClassifier()
model.load_model(MODEL_PATH / 'xgboost.json')

In [28]:
model.feature_names_in_

array(['amount', 'type_CASH_IN', 'type_CASH_OUT', 'type_DEBIT',
       'type_PAYMENT', 'type_TRANSFER', 'orig_tx_count_same_step',
       'orig_tx_cumcount', 'orig_prev_amount', 'orig_amount_ratio',
       'steps_since_last_tx', 'dest_tx_cumcount', 'dest_prev_amount',
       'dest_amount_ratio', 'dest_steps_since_last', 'pair_tx_cumcount',
       'is_new_dest', 'pair_total_amount', 'hour_of_day', 'day',
       'is_night'], dtype='<U23')

In [34]:
model.predict(transaction)

array([1, 1, 1])

In [ ]:
model.predict_proba(transaction)

array([[0.04786026, 0.95213974],
       [0.08882904, 0.91117096],
       [0.11950386, 0.88049614]], dtype=float32)

: